Models/ViewModels/Author/DossierAuthorViewModel.cs
using linc.Data;
using System.ComponentModel.DataAnnotations;

namespace linc.Models.ViewModels.Author
{
    public class DossierAuthorViewModel
    {
        public int? Id { get; set; }

        public int DossierId { get; set; }

        [Required(ErrorMessageResourceName = "RequiredAttribute_ValidationError", ErrorMessageResourceType = typeof(Resources.ValidationResource))]
        [MaxLength(255, ErrorMessageResourceName = "MaxLengthAttribute_ValidationError", ErrorMessageResourceType = typeof(Resources.ValidationResource))]
        [Display(Name = "Author_FirstName", ResourceType = typeof(Resources.SharedResource))]
        public string FirstName { get; set; }

        [Required(ErrorMessageResourceName = "RequiredAttribute_ValidationError", ErrorMessageResourceType = typeof(Resources.ValidationResource))]
        [MaxLength(255, ErrorMessageResourceName = "MaxLengthAttribute_ValidationError", ErrorMessageResourceType = typeof(Resources.ValidationResource))]
        [Display(Name = "Author_LastName", ResourceType = typeof(Resources.SharedResource))]
        public string LastName { get; set; }

        [Required(ErrorMessageResourceName = "RequiredAttribute_ValidationError", ErrorMessageResourceType = typeof(Resources.ValidationResource))]
        [EmailAddress(ErrorMessageResourceName = "EmailAddressAttribute_Invalid", ErrorMessageResourceType = typeof(Resources.ValidationResource))]
        [MaxLength(255, ErrorMessageResourceName = "MaxLengthAttribute_ValidationError", ErrorMessageResourceType = typeof(Resources.ValidationResource))]
        [Display(Name = "Author_Email", ResourceType = typeof(Resources.SharedResource))]
        public string Email { get; set; }

        [MaxLength(127)]
        public string UserId { get; set; }

        [Display(Name = "Author_UserName", ResourceType = typeof(Resources.SharedResource))]
        public string UserName { get; set; }


        [Display(Name = "DocumentType_Agreement", ResourceType = typeof(Resources.SharedResource))]
        public ApplicationDocument Agreement { get; set; }

        public int? AgreementId { get; set; }


        [Display(Name = "DossierEdit_Agreement", ResourceType = typeof(Resources.SharedResource))]
        public IFormFile AgreementDocument { get; set; }
    }
}

Models/ViewModels/Home/AuthorsViewModel.cs
namespace linc.Models.ViewModels.Home
{
    public class AuthorsViewModel
    {
    }
}

Controllers/AuthorController.cs
using linc.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace linc.Controllers
{
    public class AuthorController : BaseController
    {
        private readonly IAuthorService _authorService;

        public AuthorController(ILocalizationService localizationService, IAuthorService authorService)
            : base(localizationService)
        {
            _authorService = authorService;
        }

        [HttpGet]
        public async Task<IActionResult> Search(int? languageId, string q)
        {
            if (string.IsNullOrWhiteSpace(q))
            {
                return BadRequest($"Search term '{nameof(q)}' is required.");
            }

            if (q.Length < 3)
            {
                return BadRequest($"Search term '{nameof(q)}' must be at least 3 characters long.");
            }

            languageId ??= LocalizationService.GetCurrentLanguageId();

            var authors = await _authorService.SearchAuthorsAsync(languageId.Value, q);

            return Json(authors);
        }
    }
}

Controllers/DocumentController.cs
using linc.Contracts;
using linc.Models.Enumerations;
using linc.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mime;

namespace linc.Controllers
{
    public class DocumentController : BaseController
    {
        private readonly IDocumentService _documentService;
        private readonly ILogger<DocumentController> _logger;
        private readonly IDossierService _dossierService;
        private readonly ISourceService _sourceService;
        private readonly IIssueService _issueService;

        public DocumentController(
            IIssueService issueService,
            ISourceService sourceService,
            IDossierService dossierService,
            IDocumentService documentService,
            ILocalizationService localizationService, 
            ILogger<DocumentController> logger) 
            : base(localizationService)
        {
            _logger = logger;
            _documentService = documentService;
            _dossierService = dossierService;
            _issueService = issueService;
            _sourceService = sourceService;
        }

        [HttpGet("issue/{issueId:int}/document/{documentId:int?}", Name = nameof(LoadIssueDocument))]
        [AllowAnonymous]
        public async Task<IActionResult> LoadIssueDocument(int issueId, int? documentId, bool download = false)
        {
            // NOTE: documentId can be nullable here in order to return the pdf as the default document if no documentId is passed
            var issueDocument = await _issueService.GetIssueDocumentAsync(issueId, documentId);
            if (issueDocument is null)
            {
                return NotFound();
            }

            var result = await GetDocumentFile(issueDocument.Id, download);
            if (result is null)
            {
                return NotFound();
            }

            return result;
        }

        [HttpGet("source/{sourceId:int}/document")]
        [AllowAnonymous]
        public async Task<IActionResult> LoadSourceDocument(int sourceId, bool download = false)
        {
            var source = await _sourceService.GetSourceAsync(sourceId);
            if (source is null)
            {
                return NotFound();
            }

            var result = await GetDocumentFile(source.PdfId, download);
            if (result is null)
            {
                return NotFound();
            }

            return result;
        }

        [HttpGet("dossier/{dossierId:int}/document/{documentId:int}")]
        [SiteAuthorize(SiteRole.Editor)]
        public async Task<IActionResult> LoadDossierDocument(int dossierId, int documentId, bool download = true)
        {
            // NOTE: most of the time one would wish to download the dossier file so download is true by default

            var dossierDocument = await _dossierService.GetDossierDocumentAsync(dossierId, documentId);
            if (dossierDocument == null)
            {
                return NotFound();
            }

            var result = await GetDocumentFile(documentId, download);
            if (result is null)
            {
                return NotFound();
            }

            return result;
        }

        private async Task<PhysicalFileResult> GetDocumentFile(int documentId, bool download = false)
        {
            var document = await _documentService.GetDocumentAsync(documentId);
            if (document is null)
            {
                return null;
            }

            var path = _documentService.GetDocumentFilePath(document);
            if (path is null)
            {
                return null;
            }

            PhysicalFileResult result;

            // don't append FileDownloadName by default since we do not want to force
            // browsers to download the file, but instead attempt to display it

            if (download)
            {
                result = new PhysicalFileResult(path, MediaTypeNames.Application.Octet)
                {
                    FileDownloadName = document.OriginalFileName
                };
            }
            else
            {
                result = new PhysicalFileResult(path, document.MimeType);
            }

            _logger.LogInformation("Sending document file {Path} with MimeType of {MimeType} and type {DocumentType} for download: {Download}",
                path, document.MimeType, document.DocumentType.ToString(), download);

            return result;
        }
    }
}

Controllers/IssueController.cs
using linc.Contracts;
using Microsoft.AspNetCore.Mvc;
using linc.Models.Enumerations;
using linc.Models.ViewModels.Issue;
using linc.Utility;
using linc.Services;

namespace linc.Controllers
{
    public class IssueController : BaseController
    {
        private readonly ILogger<IssueController> _logger;
        private readonly IIssueService _issueService;

        public IssueController(
            ILocalizationService localizationService,
            ILogger<IssueController> logger,
            IIssueService issueService)
            : base(localizationService)
        {
            _logger = logger;
            _issueService = issueService;
        }

        // TODO
        // public async Task<IActionResult> Index(int? page, int? year, string filter, int? issueId)
        // {
        //     filter = System.Net.WebUtility.UrlDecode(filter);
        //     var languageId = LocalizationService.GetCurrentLanguageId();
        //     var viewModel = await _sourceService.GetSourcesPagedAsync(filter: filter, languageId: languageId,
        //         year: year, issueId: issueId, pageIndex: page);
        //
        //     viewModel.YearFilter = await _sourceService.GetSourcesCountByYears();
        //     viewModel.IssuesFilter = await _sourceService.GetSourcesCountByIssues();
        //
        //     viewModel.AuthorsFilter = filter;
        //     viewModel.CurrentIssueId = issueId;
        //     viewModel.CurrentAuthorsFilter = filter;
        //     viewModel.CurrentYearFilter = year;
        //
        //     return View(viewModel);
        // }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentLanguageId = LocalizationService.GetCurrentLanguageId();
            var issue = await _issueService.GetIssueAsync(id.Value, currentLanguageId);
            if (issue == null)
            {
                _logger.LogWarning("Could not find issue with the id of {@Id}", id.Value);
                return NotFound();
            }

            if (!issue.IsAvailable && !User.IsAtLeast(SiteRole.UserPlus))
            {
                return NotFound();
            }

            _logger.LogInformation("Loading issue {Id}", id.Value);

            return View(issue);
        }

        [SiteAuthorize(SiteRole.Editor)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SiteAuthorize(SiteRole.Editor)]
        public async Task<IActionResult> Create(IssueCreateViewModel vModel) 
        {
            if (!ModelState.IsValid)
            {
                return View(vModel);
            }

            var issueId = await _issueService.CreateIssueAsync(vModel);

            _logger.LogInformation("Issue {IssueId} has been created successfully, redirecting...",
                issueId);

            return RedirectToAction(nameof(Details), new { id = issueId });
        }
    }
}

Controllers/SourceController.cs
using linc.Contracts;
using Microsoft.AspNetCore.Mvc;
using linc.Models.Enumerations;
using linc.Utility;
using Microsoft.AspNetCore.Mvc.Rendering;
using linc.Models.ViewModels.Source;

namespace linc.Controllers
{
    public class SourceController : BaseController
    {
        private readonly ILogger<SourceController> _logger;
        private readonly ISourceService _sourceService;
        private readonly IIssueService _issuesService;

        public SourceController(
            ILocalizationService localizationService,
            ILogger<SourceController> logger,
            ISourceService sourceService, 
            IIssueService issuesService)
            : base(localizationService)
        {
            _logger = logger;
            _sourceService = sourceService;
            _issuesService = issuesService;
        }

        public async Task<IActionResult> Index(int? page, int? year, string filter, int? issueId)
        {
            filter = System.Net.WebUtility.UrlDecode(filter);
            var languageId = LocalizationService.GetCurrentLanguageId();
            var viewModel = await _sourceService.GetSourcesPagedAsync(filter: filter, languageId: languageId, 
                year: year, issueId: issueId, pageIndex: page);
            
            viewModel.YearFilter = await _sourceService.GetSourcesCountByYears();
            viewModel.IssuesFilter = await _sourceService.GetSourcesCountByIssues();

            viewModel.AuthorsFilter = filter;
            viewModel.CurrentIssueId = issueId;
            viewModel.CurrentAuthorsFilter = filter;
            viewModel.CurrentYearFilter = year;

            return View(viewModel);
        }

        [SiteAuthorize(SiteRole.Editor)]
        public async Task<IActionResult> Admin(int? page)
        {
            var languageId = LocalizationService.GetCurrentLanguageId();
            var viewModel = await _sourceService.GetAdminSourcesPagedAsync(languageId: languageId, pageIndex: page);

            return View(viewModel);
        }

        [SiteAuthorize(SiteRole.Editor)]
        public async Task<IActionResult> Create()
        {
            var vModel = new SourceCreateViewModel
            {
                Issues = await GetIssuesAsync(),
                Languages = GetLanguages(),

                LanguageId = LocalizationService.GetCurrentLanguageId()
            };

            return View(vModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SiteAuthorize(SiteRole.Editor)]
        public async Task<IActionResult> Create(SourceCreateViewModel vModel) 
        {
            if (!ModelState.IsValid)
            {
                vModel.Issues = await GetIssuesAsync(vModel.IssueId);
                vModel.Languages = GetLanguages(vModel.LanguageId);

                vModel.LanguageId = LocalizationService.GetCurrentLanguageId();

                return View(vModel);
            }

            var sourceId = await _sourceService.CreateSourceAsync(vModel);

            _logger.LogInformation("Source {SourceId} has been created successfully, redirecting...", 
                sourceId);

            return RedirectToAction("Edit", new { id = sourceId });
        }

        [SiteAuthorize(SiteRole.HeadEditor)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var source = await _sourceService.GetSourceAsync(id.Value);
            if (source == null)
            {
                return NotFound();
            }

            var vModel = new SourceUpdateViewModel()
            {
                Id = source.Id,
                Title = source.Title,
                TitleNotes = source.TitleNotes,

                DOI = source.DOI,

                FirstName = source.FirstName,
                LastName = source.LastName,
                AuthorNotes = source.AuthorNotes,

                StartingPdfPage = source.StartingPdfPage,
                LastPdfPage = source.LastPdfPage,

                StartingIndexPage = source.StartingIndexPage,

                IssueId = source.IssueId,
                LanguageId = source.LanguageId,

                IsTheme = source.IsTheme,
                IsSection = source.IsSection,

                Issues = await GetIssuesAsync(source.IssueId),
                Languages = GetLanguages(source.LanguageId),

                LastUpdated = source.LastUpdated,
                DateCreated = source.DateCreated,
            };

            return View(vModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SiteAuthorize(SiteRole.Administrator)]
        public async Task<IActionResult> Edit(SourceUpdateViewModel vModel)
        {
            if (!ModelState.IsValid)
            {
                vModel.Issues = await GetIssuesAsync(vModel.IssueId);
                vModel.Languages = GetLanguages(vModel.LanguageId);

                return View(vModel);
            }

            await _sourceService.UpdateSourceAsync(vModel);
            return RedirectToAction(nameof(Admin));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SiteAuthorize(SiteRole.Administrator)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _sourceService.DeleteSourceAsync(id.Value);
            return RedirectToAction(nameof(Admin));
        }

        private async Task<List<SelectListItem>> GetIssuesAsync(int? issueId = null)
        {
            var issues = await _issuesService.GetIssuesAsync();
            return issues.Select(x => new SelectListItem(
                    IIssueService.DisplayIssueLabelInformation(x.IssueNumber, x.ReleaseYear), 
                    x.Id.ToString(),
                    x.Id == issueId))
                .ToList();
        }

        private List<SelectListItem> GetLanguages(int? languageId = null)
        {
            var currentLanguageId = LocalizationService.GetCurrentLanguageId();
            var list = SiteConstant.SupportedCultures.Select(supportedCulture =>
                    new SelectListItem(
                        supportedCulture.Value, 
                        supportedCulture.Key.ToString(),
                        languageId.HasValue ? supportedCulture.Key == languageId :
                            supportedCulture.Key == currentLanguageId))
                .ToList();

            return list;
        }
    }
}

Views/Source/Index.cshtml
@using linc.Utility
@using System.Net
@using System.Web
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model SourceIndexViewModel

@{
    ViewData["Title"] = HtmlLocalizer["Source_IndexPage_Title"];
    ViewData["Area"] = SiteConstant.LandingPageArea;
}

@section Breadcrumbs {
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">

            <div class="d-flex justify-content-between align-items-center">
                <h2>@HtmlLocalizer["Source_IndexPage_SubTitle"]</h2>
                <ol>
                    <li>
                        <a href="/">@HtmlLocalizer["NavItem_Home"]</a>
                    </li>
                    @if (Model.AuthorsFilter?.Length > 1)
                    {
                        <li>
                            <a asp-controller="Source" asp-action="Index">@ViewData["Title"]</a>
                        </li>

                        <li>@Model.AuthorsFilter</li>
                    }
                    else
                    {
                        <li>@ViewData["Title"]</li>
                    }
                </ol>
            </div>

        </div>
    </section>
    <!-- End Breadcrumbs -->
}

<section class="portfolio-details">
    <div class="container">
        <div class="row">
            
            <small class="pb-3">@HtmlLocalizer["Source_IndexPage_SearchDescription"]</small>

            <div class="col-md-8">

                <div class="alphabet-sort">

                    <div class="alphabet-wildcard alphabet-letter clear">
                        <a href="@Url.Action("Index", "Source", new { year = Model.CurrentYearFilter, issueId = Model.CurrentIssueId })">
                            <i class="bi bi-asterisk"></i>
                        </a>
                    </div>

                    <div class="row">
                        @foreach (var letter in SiteConstant.CyrillicAlphabet.Select(x => x.ToString()))
                        {
                            <div class="alphabet-letter @(Model.CurrentAuthorsFilter == letter ? "active" : "")">
                                <a href="@Url.Action("Index", "Source", new { filter = WebUtility.UrlEncode(letter), year = Model.CurrentYearFilter, issueId = Model.CurrentIssueId })">@letter</a>
                            </div>
                        }
                    </div>

                    <div class="row">
                        @foreach (var letter in SiteConstant.LatinAlphabet.Select(x => x.ToString()))
                        {
                            <div class="alphabet-letter @(Model.CurrentAuthorsFilter == letter ? "active" : "")">
                                <a href="@Url.Action("Index", "Source", new { filter = WebUtility.UrlEncode(letter), year = Model.CurrentYearFilter, issueId = Model.CurrentIssueId })">@letter</a>
                            </div>
                        }
                    </div>

                </div>

                <div id="list-source" class="content" role="main">

                    @if (Model.Records.Any())
                    {
                        <ul>
                            @foreach (var source in Model.Records)
                            {
                                <li class="source-container">

                                    <div class="source-origin-container">
                                        <p class="source-orgin">
                                            <small>
                                                <a asp-controller="Issue" asp-action="Details" asp-route-id="@source.IssueId">
                                                    @IIssueService.DisplayIssueLabelInformation(source.Issue.IssueNumber, source.Issue.ReleaseYear)
                                                </a>
                                            </small>
                                        </p>
                                    </div>

                                    @if (!string.IsNullOrWhiteSpace(source.AuthorNames))
                                    {
                                        <p class="source-author annotate">
                                            @source.AuthorNames
                                            @if (!string.IsNullOrEmpty(source.AuthorNotes))
                                            {
                                                <br/>
                                                <small>
                                                    @Html.Raw(source.AuthorNotes.ReplaceLineEndings("<br>"))
                                                </small>
                                            }
                                        </p>
                                    }

                                    @if (!string.IsNullOrWhiteSpace(source.DOI))
                                    {
                                        <p class="source-doi">
                                            <a href="@source.DOI" target="_blank">
                                                <small>@source.DOI <sup><i class="bi bi-box-arrow-up-right"></i></sup></small>
                                            </a>
                                        </p>
                                    }

                                    <p class="source-title annotate">
                                        <a href="@Url.Action("LoadSourceDocument", "Document", new { sourceId = source.Id })" target="_blank">@source.Title</a>
                                    </p>

                                    <p class="source-page text-end">
                                        <strong><a href="@Url.Action("LoadIssueDocument", "Document", new { issueId = source.IssueId })#page=@source.StartingPdfPage" target="_blank">@source.StartingIndexPage</a></strong>
                                    </p>

                                    @if (!string.IsNullOrEmpty(source.TitleNotes))
                                    {
                                        <small class="annotate">@source.TitleNotes</small>
                                    }

                                </li>
                            }
                        </ul>
                    }
                    else
                    {
                        <p>
                            @HtmlLocalizer["Source_IndexPage_NoResults"]
                        </p>
                    }

                    @if (Model.TotalPages > 1)
                    {
                        @await Html.PartialAsync("_Paging", Model)
                    }

                </div>
            </div>

            <div class="col-md-4 text-end">

                <div class="portfolio-description">
                    <h2>@HtmlLocalizer["Source_IndexPage_FilterByYears_Title"]</h2>
                    <p>
                        <ul class="icon-links">
                            <li>
                                <i class="bx bx-chevron-right"></i>
                                <a class="@(Model.CurrentYearFilter.HasValue ? string.Empty : "active")" href="@Url.Action("Index", "Source")">
                                    @HtmlLocalizer["All_Label"]
                                </a>
                            </li>
                            @foreach (var filter in Model.YearFilter)
                            {
                                <li>
                                    <i class="bx bx-chevron-right"></i>
                                    <a class="@(Model.CurrentYearFilter == filter.Year ? "active" : "")" href="@Url.Action("Index", "Source", new { year = filter.Year })">
                                        @filter.Year (@filter.Count)
                                    </a>
                                </li>
                            }
                        </ul>
                    </p>
                    <h2>@HtmlLocalizer["Source_IndexPage_FilterByIssues_Title"]</h2>
                    <p>
                        <ul class="icon-links">
                            <li>
                                <i class="bx bx-chevron-right"></i>
                                <a class="@(Model.CurrentIssueId.HasValue ? string.Empty : "active")" href="@Url.Action("Index", "Source")">
                                    @HtmlLocalizer["All_Label"]
                                </a>
                            </li>
                            @foreach (var filter in Model.IssuesFilter)
                            {
                                <li>
                                    <i class="bx bx-chevron-right"></i>
                                    <a class="@(Model.CurrentIssueId == filter.IssueId ? "active" : "")" href="@Url.Action("Index", "Source", new { issueId = filter.IssueId })">
                                        @filter.IssueTitle (@filter.Count)
                                    </a>
                                </li>
                            }
                        </ul>
                    </p>
                </div>

            </div>
        </div>
    </div>
</section>

@section Newsletter {
    <partial name="Newsletter/_Submit" />
}

@{

    var safeSearchQuery = "";
    if (Model.AuthorsFilter?.Length > 1)
    {
        safeSearchQuery = HttpUtility.JavaScriptStringEncode(Model.AuthorsFilter);
    }
}

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#nav-sources").addClass('active');
            
            function decodeHtmlEntities(encodedString) {
                let textArea = document.createElement('textarea');
                textArea.innerHTML = encodedString;
                return textArea.value;
            }

            let encodedSearchQuery = '@safeSearchQuery';
            let searchQuery = decodeHtmlEntities(encodedSearchQuery);
            
            if(!searchQuery) {
                // nothing to do here
                // cease execution
                return;
            }

            //console.log(searchQuery);

            function highlightSearchQuery(textContent, searchQuery) {
                // Escape special regex characters in searchQuery
                let escapedSearchQuery = searchQuery.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
                let regex = new RegExp(escapedSearchQuery, 'gi'); // 'g' for global search, 'i' for case-insensitive

                return textContent.replace(regex, function (match) {
                    return `<span class="highlight">${match}</span>`;
                });
            }

            $(".annotate").each(function (index, element) {
                element.innerHTML = highlightSearchQuery(element.innerHTML, searchQuery)
            });
        })
    </script>
}